// AUTO-GENERATED — DO NOT EDIT BY HAND.
//
// Regenerate with `pnpm tour:codegen`.
//
// Source of truth: every `data-tour="value"` JSX attribute under
// apps/web/src (recursively, .tsx only). The codegen script walks
// that tree and collects unique values; this file is the typed
// projection used by the tour-registry, admin picker, and any other
// tour-aware consumer.
export const TOUR_TARGETS = [
  "add-asset-btn",
  "add-asset-category-btn",
  "add-location-btn",
  "add-role-btn",
  "add-row-btn",
  "add-user-btn",
  "asset-categories-table",
  "asset-create",
  "asset-detail",
  "asset-edit",
  "asset-import",
  "asset-list",
  "asset-rows",
  "asset-search",
  "audit-action-filter",
  "audit-card-list",
  "audit-date-from",
  "audit-date-to",
  "audit-export-btn",
  "audit-filter-bar",
  "audit-page",
  "audit-page-size",
  "audit-page-title",
  "audit-pagination",
  "audit-resource-type-filter",
  "audit-search-input",
  "audit-table",
  "audit-table-row",
  "audit-user-filter",
  "barcode-scanner",
  "bulk-actions-bar",
  "category-filter",
  "columns-menu",
  "confirm-import-btn",
  "create-report-btn",
  "dashboard-alerts",
  "dashboard-charts",
  "dashboard-recent-movements",
  "dashboard-summary",
  "download-import-template-btn",
  "download-report-btn",
  "export-assets-btn",
  "generate-report-btn",
  "import-assets-btn",
  "import-file-input",
  "label-printing",
  "location-tree",
  "location-tree-picker",
  "login-form",
  "maintenance",
  "mark-all-read-btn",
  "movement-list",
  "new-product-btn",
  "notification-bell",
  "notification-read-filter",
  "notification-type-filter",
  "notifications-page",
  "report-create",
  "report-detail",
  "report-detail-download-btn",
  "report-detail-generate-btn",
  "report-name-input",
  "report-type-filter",
  "report-type-select",
  "reports-list",
  "role-management",
  "save-report-btn",
  "saved-views-menu",
  "scan-product-btn",
  "sidebar-nav",
  "status-filter",
  "upload-validate-btn",
  "user-management",
  "user-search",
] as const;

export type TourTargetValue = (typeof TOUR_TARGETS)[number];
